branch-defaults:
  dev:
    environment: udagram-cbr-dev-dev
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-cbr-dev
  branch: null
  default_ec2_keyname: udagram-mono-dev
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
